name: Documentation request
description: Request a new doc or major improvement.
labels: ["docs", "discussion"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true

  - type: textarea
    id: audience
    attributes:
      label: Intended audience
      description: "e.g. validator authors, model contributors, maintainers"
    validations:
      required: true

